// <auto-generated />
using System;
using BookLoggerApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLoggerApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410160000_AddSlotWidthToShopItem")]
    partial class AddSlotWidthToShopItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BookLoggerApp.Core.Models.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoBackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCompletedOnboarding")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideGettingStartedCta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("OnboardingAutoCompletedForExistingUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnboardingCurrentStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnboardingFlowVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnboardingIntroStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnboardingTutorialPlantNeedsWateringAssist")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadingRemindersEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShelfBaseColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShelfLedgeColor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelemetryEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalXp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantsPurchased")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-0000-0000-0000-000000000001"),
                            AutoBackupEnabled = false,
                            Coins = 100,
                            HasCompletedOnboarding = false,
                            HideGettingStartedCta = false,
                            Language = "en",
                            OnboardingAutoCompletedForExistingUser = 0,
                            OnboardingCurrentStep = 0,
                            OnboardingFlowVersion = 2,
                            OnboardingIntroStatus = 0,
                            OnboardingTutorialPlantNeedsWateringAssist = false,
                            NotificationsEnabled = false,
                            PlantsPurchased = 0,
                            ReadingRemindersEnabled = false,
                            ShelfBaseColor = "#D4A574",
                            ShelfLedgeColor = "#8B7355",
                            TelemetryEnabled = false,
                            Theme = "Light",
                            TotalXp = 0,
                            UserLevel = 1
                        });
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.ShopItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlantSpeciesId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("SlotWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("ItemType");

                    b.HasIndex("PlantSpeciesId");

                    b.HasIndex("UnlockLevel");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new { Id = new Guid("20000000-0000-0000-0000-000000000001"), Cost = 100, Description = "A warm flickering candle — the perfect reading companion.", ImagePath = "images/decorations/candle.svg", IsAvailable = true, ItemType = 2, Name = "Reading Candle", SlotWidth = 1, UnlockLevel = 1 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000002"), Cost = 120, Description = "A ceramic mug with a book-spine pattern. Always full.", ImagePath = "images/decorations/mug.svg", IsAvailable = true, ItemType = 2, Name = "Cosy Book Mug", SlotWidth = 1, UnlockLevel = 1 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000003"), Cost = 150, Description = "A hand-carved oak bookend. Your books deserve a proper brace.", ImagePath = "images/decorations/bookend_wood.svg", IsAvailable = true, ItemType = 2, Name = "Wooden Bookend", SlotWidth = 1, UnlockLevel = 1 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000004"), Cost = 175, Description = "Measure your reading sessions in style.", ImagePath = "images/decorations/hourglass.svg", IsAvailable = true, ItemType = 2, Name = "Brass Hourglass", SlotWidth = 1, UnlockLevel = 5 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000005"), Cost = 180, Description = "Round brass-rimmed glasses. Any shelf gains +10 distinguished.", ImagePath = "images/decorations/spectacles.svg", IsAvailable = true, ItemType = 2, Name = "Scholar's Spectacles", SlotWidth = 1, UnlockLevel = 5 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000006"), Cost = 200, Description = "A glass inkwell with a raven feather quill. Timeless.", ImagePath = "images/decorations/inkwell.svg", IsAvailable = true, ItemType = 2, Name = "Inkwell & Quill", SlotWidth = 1, UnlockLevel = 10 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000007"), Cost = 220, Description = "A ceramic owl. Wise observer of your reading habits.", ImagePath = "images/decorations/owl_figurine.svg", IsAvailable = true, ItemType = 2, Name = "Owl Figurine", SlotWidth = 1, UnlockLevel = 10 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000008"), Cost = 260, Description = "A vintage brass globe. Explore worlds between the shelves.", ImagePath = "images/decorations/globe.svg", IsAvailable = true, ItemType = 2, Name = "Library Globe", SlotWidth = 2, UnlockLevel = 15 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000009"), Cost = 280, Description = "Carved marble bookends — heavy, elegant, permanent.", ImagePath = "images/decorations/bookend_marble.svg", IsAvailable = true, ItemType = 2, Name = "Marble Bookend", SlotWidth = 2, UnlockLevel = 15 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000010"), Cost = 320, Description = "A miniature brass telescope. For reading between the stars.", ImagePath = "images/decorations/telescope.svg", IsAvailable = true, ItemType = 2, Name = "Brass Telescope", SlotWidth = 2, UnlockLevel = 20 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000011"), Cost = 340, Description = "An enchanted desk lamp that never runs out of oil.", ImagePath = "images/decorations/magic_lamp.svg", IsAvailable = true, ItemType = 2, Name = "Magic Reading Lamp", SlotWidth = 1, UnlockLevel = 20 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000012"), Cost = 360, Description = "A tiny dragon perched on your shelf. He's read everything.", ImagePath = "images/decorations/dragon_figurine.svg", IsAvailable = true, ItemType = 2, Name = "Dragon Figurine", SlotWidth = 1, UnlockLevel = 25 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000013"), Cost = 380, Description = "A glowing green flask of unknown purpose. Do not drink.", ImagePath = "images/decorations/alchemy_flask.svg", IsAvailable = true, ItemType = 2, Name = "Alchemy Flask", SlotWidth = 1, UnlockLevel = 25 },
                        new { Id = new Guid("20000000-0000-0000-0000-000000000014"), Cost = 400, Description = "A sealed scroll of immense wisdom. Or a grocery list. Who knows.", ImagePath = "images/decorations/ancient_scroll.svg", IsAvailable = true, ItemType = 2, Name = "Ancient Scroll", SlotWidth = 2, UnlockLevel = 25 }
                    );
                });

#pragma warning restore 612, 618
        }
    }
}