// <auto-generated />
using System;
using BookLoggerApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLoggerApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214123940_AddGoalGenres")]
    partial class AddGoalGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("BookLoggerApp.Core.Models.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("PageNumber");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoBackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastBackupDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantsPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadingRemindersEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("ReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<bool>("TelemetryEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalXp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-0000-0000-0000-000000000001"),
                            AutoBackupEnabled = false,
                            Coins = 100,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "en",
                            NotificationsEnabled = false,
                            PlantsPurchased = 0,
                            ReadingRemindersEnabled = false,
                            TelemetryEnabled = false,
                            Theme = "Light",
                            TotalXp = 0,
                            UserLevel = 1
                        });
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookshelfPosition")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CharactersRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PacingRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlotRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int?>("SpiceLevelRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpineColor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsesCoverAsSpine")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorldBuildingRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WritingStyleRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateAdded");

                    b.HasIndex("ISBN");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.BookGenre", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BookGenres");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.BookRatingSummary", b =>
                {
                    b.Property<double>("AverageRating")
                        .HasColumnType("REAL");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.HasIndex("BookId");

                    b.ToTable("BookRatingSummaries");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.BookShelf", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShelfId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "ShelfId");

                    b.HasIndex("ShelfId");

                    b.ToTable("BookShelves");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.BookTrope", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TropeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId", "TropeId");

                    b.HasIndex("TropeId");

                    b.ToTable("BookTropes");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ColorHex = "#3498db",
                            Icon = "📖",
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ColorHex = "#2ecc71",
                            Icon = "📚",
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ColorHex = "#9b59b6",
                            Icon = "🧙",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            ColorHex = "#1abc9c",
                            Icon = "🚀",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            ColorHex = "#e74c3c",
                            Icon = "🔍",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            ColorHex = "#e91e63",
                            Icon = "💕",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            ColorHex = "#f39c12",
                            Icon = "👤",
                            Name = "Biography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            ColorHex = "#95a5a6",
                            Icon = "📜",
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            ColorHex = "#880e4f",
                            Icon = "🖤",
                            Name = "Dark Romance"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            ColorHex = "#34495e",
                            Icon = "🔦",
                            Name = "Krimi"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            ColorHex = "#f1c40f",
                            Icon = "🎭",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            ColorHex = "#c0392b",
                            Icon = "😱",
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.GoalExcludedBook", b =>
                {
                    b.Property<Guid>("ReadingGoalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.HasKey("ReadingGoalId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("GoalExcludedBooks");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.GoalGenre", b =>
                {
                    b.Property<Guid>("ReadingGoalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT");

                    b.HasKey("ReadingGoalId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GoalGenres");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.PlantShelf", b =>
                {
                    b.Property<Guid>("PlantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShelfId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlantId", "ShelfId");

                    b.HasIndex("ShelfId");

                    b.ToTable("PlantShelves");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.PlantSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("GrowthRate")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaterIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("XpBoostPercentage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UnlockLevel");

                    b.ToTable("PlantSpecies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BaseCost = 500,
                            Description = "A simple plant for beginners. Grows quickly!",
                            GrowthRate = 1.2,
                            ImagePath = "images/plants/starter_sprout.svg",
                            IsAvailable = true,
                            MaxLevel = 10,
                            Name = "Starter Sprout",
                            UnlockLevel = 1,
                            WaterIntervalDays = 3,
                            XpBoostPercentage = 0.05m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            BaseCost = 600,
                            Description = "A growing seedling nurtured by stories.",
                            GrowthRate = 1.1000000000000001,
                            ImagePath = "images/plants/story_seedling.svg",
                            IsAvailable = true,
                            MaxLevel = 11,
                            Name = "Story Seedling",
                            UnlockLevel = 3,
                            WaterIntervalDays = 4,
                            XpBoostPercentage = 0.06m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            BaseCost = 750,
                            Description = "A lush fern for dedicated readers.",
                            GrowthRate = 1.0,
                            ImagePath = "images/plants/bookworm_fern.svg",
                            IsAvailable = true,
                            MaxLevel = 12,
                            Name = "Bookworm Fern",
                            UnlockLevel = 8,
                            WaterIntervalDays = 4,
                            XpBoostPercentage = 0.08m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            BaseCost = 850,
                            Description = "A beautiful lily that blooms with every chapter.",
                            GrowthRate = 0.90000000000000002,
                            ImagePath = "images/plants/literary_lily.svg",
                            IsAvailable = true,
                            MaxLevel = 14,
                            Name = "Literary Lily",
                            UnlockLevel = 14,
                            WaterIntervalDays = 5,
                            XpBoostPercentage = 0.09m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            BaseCost = 1000,
                            Description = "Low maintenance, high rewards.",
                            GrowthRate = 0.80000000000000004,
                            ImagePath = "images/plants/reading_cactus.svg",
                            IsAvailable = true,
                            MaxLevel = 15,
                            Name = "Reading Cactus",
                            UnlockLevel = 21,
                            WaterIntervalDays = 7,
                            XpBoostPercentage = 0.10m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            BaseCost = 1500,
                            Description = "A wise tree that stands the test of time.",
                            GrowthRate = 0.69999999999999996,
                            ImagePath = "images/plants/wisdom_willow.svg",
                            IsAvailable = true,
                            MaxLevel = 18,
                            Name = "Wisdom Willow",
                            UnlockLevel = 28,
                            WaterIntervalDays = 8,
                            XpBoostPercentage = 0.12m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            BaseCost = 2500,
                            Description = "An ancient bonsai radiating knowledge.",
                            GrowthRate = 0.59999999999999998,
                            ImagePath = "images/plants/ancient_bonsai.svg",
                            IsAvailable = true,
                            MaxLevel = 20,
                            Name = "Ancient Knowledge Bonsai",
                            UnlockLevel = 31,
                            WaterIntervalDays = 10,
                            XpBoostPercentage = 0.15m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            BaseCost = 5000,
                            Description = "A legendary tree with leaves like parchment.",
                            GrowthRate = 0.5,
                            ImagePath = "images/plants/mystic_tome_tree.svg",
                            IsAvailable = true,
                            MaxLevel = 25,
                            Name = "Mystic Tome Tree",
                            UnlockLevel = 33,
                            WaterIntervalDays = 14,
                            XpBoostPercentage = 0.20m
                        });
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("IsFavorite");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.ReadingGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Current")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("StartDate");

                    b.ToTable("ReadingGoals");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.ReadingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndPage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PagesRead")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int?>("StartPage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("StartedAt");

                    b.ToTable("ReadingSessions");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Shelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutoSortRule")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Shelves");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.ShopItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlantSpeciesId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("ItemType");

                    b.HasIndex("PlantSpeciesId");

                    b.HasIndex("UnlockLevel");

                    b.ToTable("ShopItems");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Trope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Tropes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06232a7b-a3cf-4cb6-e391-1c1416bb6393"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "The Chosen One"
                        },
                        new
                        {
                            Id = new Guid("f0eae802-8660-d175-9124-fc7e06ce35e2"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Dark Lord"
                        },
                        new
                        {
                            Id = new Guid("4e6a5bd9-369a-6847-d3f5-3f3f984f08ba"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Quest/Journey"
                        },
                        new
                        {
                            Id = new Guid("f38f69a8-8bee-cf86-f486-8607094b5d87"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Magical Academy"
                        },
                        new
                        {
                            Id = new Guid("5dbf924c-bed7-4c27-e962-92031de0f005"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Found Family"
                        },
                        new
                        {
                            Id = new Guid("5485fd65-af73-56a2-a85b-c3c1969a71dd"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Prophecy"
                        },
                        new
                        {
                            Id = new Guid("6cd9d130-dedb-5c43-f14a-1804bb24460e"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Reluctant Hero"
                        },
                        new
                        {
                            Id = new Guid("25468a69-fe84-d76c-7e38-6f161136c3f4"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Magic System"
                        },
                        new
                        {
                            Id = new Guid("1dc08b0f-f66a-1383-89d1-7c0ee86cf71b"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Space Opera"
                        },
                        new
                        {
                            Id = new Guid("f2cab3ff-b942-e67d-705c-a0a023ee4c4b"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "First Contact"
                        },
                        new
                        {
                            Id = new Guid("27ecfac0-c48a-9dfe-0784-24f0efedd5b7"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("7f2d4be6-3796-6003-6de7-2dae984815ca"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Dystopia"
                        },
                        new
                        {
                            Id = new Guid("49552cf2-6771-54a0-f1ad-5084b04f0458"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Time Travel"
                        },
                        new
                        {
                            Id = new Guid("a5ab1333-7ced-651a-e6af-b7443ce7d9a2"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            Id = new Guid("db485dd7-0618-ef59-fa62-68596a71a0e7"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Post-Apocalyptic"
                        },
                        new
                        {
                            Id = new Guid("9d1d8d60-0f2b-d7ac-0b34-dc0c2588c438"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Enemies to Lovers"
                        },
                        new
                        {
                            Id = new Guid("a6c46a98-1a8d-5db4-8fb2-ad5ac57b7fd0"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Friends to Lovers"
                        },
                        new
                        {
                            Id = new Guid("cd935690-3e5f-7a79-1af1-75ce4ee9acbf"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Fake Dating"
                        },
                        new
                        {
                            Id = new Guid("ac7f4770-da95-0564-8002-05c3f5725523"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Second Chance"
                        },
                        new
                        {
                            Id = new Guid("225b2346-0e7f-380f-b2c6-b753885ad271"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Slow Burn"
                        },
                        new
                        {
                            Id = new Guid("c576b382-257b-8b1a-f772-42747fa6e7f7"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Grumpy x Sunshine"
                        },
                        new
                        {
                            Id = new Guid("de64dbd3-f111-89d2-867b-3b947f4b0591"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "One Bed"
                        },
                        new
                        {
                            Id = new Guid("997aff21-56c0-03b3-b009-443ada473520"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Love Triangle"
                        },
                        new
                        {
                            Id = new Guid("aabac8c9-9716-8d1f-f85a-605d6802b65b"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Forbidden Love"
                        },
                        new
                        {
                            Id = new Guid("bcf86d7a-5a84-7610-bfee-55b48021c895"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Sport Romance"
                        },
                        new
                        {
                            Id = new Guid("459f13f2-50a9-33b5-ecc9-9be1ac33e38b"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Age Gap"
                        },
                        new
                        {
                            Id = new Guid("3e760546-f353-89c0-95b6-b175c95fe25b"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Whodunit"
                        },
                        new
                        {
                            Id = new Guid("d534ca94-2dc7-b9c2-d889-5e8fccc24c53"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Locked Room"
                        },
                        new
                        {
                            Id = new Guid("44983da9-aac9-95e1-06ba-af767bfb87b3"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Unreliable Narrator"
                        },
                        new
                        {
                            Id = new Guid("5ff7530c-5283-457d-2f14-ca2d5ed3c3c6"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Red Herring"
                        },
                        new
                        {
                            Id = new Guid("e2dc894f-051b-7f30-7307-dd715f97ac41"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Noir"
                        },
                        new
                        {
                            Id = new Guid("a911fd2e-3163-7903-8c95-e20c909490d5"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Cozy Mystery"
                        },
                        new
                        {
                            Id = new Guid("f9c0966b-71b4-966b-6814-2aa3c01c75ff"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Stalker"
                        },
                        new
                        {
                            Id = new Guid("1b593009-47a6-0f35-9432-2b5547da1db8"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Captive/Captor"
                        },
                        new
                        {
                            Id = new Guid("208f5f1d-7ba3-db55-32cf-de635ae1268a"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Morally Grey MC"
                        },
                        new
                        {
                            Id = new Guid("6eed7fd4-90aa-d6f1-5582-edf9bfdfdd13"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Bully Romance"
                        },
                        new
                        {
                            Id = new Guid("5b4c3447-46e5-5da3-3661-37d4a32e3cd1"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Mafia"
                        },
                        new
                        {
                            Id = new Guid("a70c1aed-7321-998c-b263-e829a9a9553c"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Obsessive Love"
                        },
                        new
                        {
                            Id = new Guid("ff194c52-0e9e-0247-d43b-68eb1803a73d"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Enemies to Lovers"
                        },
                        new
                        {
                            Id = new Guid("1c63df2d-06cb-696e-4f4c-fa52e2184124"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Plot Twist"
                        },
                        new
                        {
                            Id = new Guid("a09ba3ec-57a1-ffee-185d-76e297cba9ac"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Psychological"
                        },
                        new
                        {
                            Id = new Guid("754c9607-0f57-29ab-2a2e-14dc8ee54446"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Serial Killer"
                        },
                        new
                        {
                            Id = new Guid("2803e766-c646-4a2a-ec0d-52f02f76350e"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Revenge"
                        },
                        new
                        {
                            Id = new Guid("70491b04-a86a-7833-0051-f474154614c6"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Spy/Espionage"
                        });
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.UserPlant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookshelfPosition")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInBookshelf")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReadingDayRecorded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWatered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadingDaysCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SpeciesId");

                    b.ToTable("UserPlants");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.WishlistInfo", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAddedToWishlist")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WishlistNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("DateAddedToWishlist");

                    b.HasIndex("Priority");

                    b.ToTable("WishlistInfos");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Annotation", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Book", "Book")
                        .WithMany("Annotations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.BookGenre", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLoggerApp.Core.Models.Genre", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.BookRatingSummary", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.BookShelf", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Book", "Book")
                        .WithMany("BookShelves")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLoggerApp.Core.Models.Shelf", "Shelf")
                        .WithMany("BookShelves")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.BookTrope", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Book", "Book")
                        .WithMany("BookTropes")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLoggerApp.Core.Models.Trope", "Trope")
                        .WithMany("BookTropes")
                        .HasForeignKey("TropeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Trope");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.GoalExcludedBook", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLoggerApp.Core.Models.ReadingGoal", "ReadingGoal")
                        .WithMany("ExcludedBooks")
                        .HasForeignKey("ReadingGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("ReadingGoal");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.GoalGenre", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLoggerApp.Core.Models.ReadingGoal", "ReadingGoal")
                        .WithMany("GoalGenres")
                        .HasForeignKey("ReadingGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("ReadingGoal");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.PlantShelf", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.UserPlant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLoggerApp.Core.Models.Shelf", "Shelf")
                        .WithMany("PlantShelves")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Quote", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Book", "Book")
                        .WithMany("Quotes")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.ReadingSession", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Book", "Book")
                        .WithMany("ReadingSessions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.ShopItem", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.PlantSpecies", "PlantSpecies")
                        .WithMany()
                        .HasForeignKey("PlantSpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlantSpecies");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Trope", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Genre", "Genre")
                        .WithMany("Tropes")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.UserPlant", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.PlantSpecies", "Species")
                        .WithMany("UserPlants")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.WishlistInfo", b =>
                {
                    b.HasOne("BookLoggerApp.Core.Models.Book", "Book")
                        .WithOne("WishlistInfo")
                        .HasForeignKey("BookLoggerApp.Core.Models.WishlistInfo", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Book", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("BookGenres");

                    b.Navigation("BookShelves");

                    b.Navigation("BookTropes");

                    b.Navigation("Quotes");

                    b.Navigation("ReadingSessions");

                    b.Navigation("WishlistInfo");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Genre", b =>
                {
                    b.Navigation("BookGenres");

                    b.Navigation("Tropes");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.PlantSpecies", b =>
                {
                    b.Navigation("UserPlants");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.ReadingGoal", b =>
                {
                    b.Navigation("ExcludedBooks");

                    b.Navigation("GoalGenres");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Shelf", b =>
                {
                    b.Navigation("BookShelves");

                    b.Navigation("PlantShelves");
                });

            modelBuilder.Entity("BookLoggerApp.Core.Models.Trope", b =>
                {
                    b.Navigation("BookTropes");
                });
#pragma warning restore 612, 618
        }
    }
}
